name: Release

on: 
  release:
    types: [created]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Build
      run: bash build_static_only_go.sh

    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: gz
        GHR_PATH: libvirt_exporter
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
