name: Release

on: 
  release:
    types: [created]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Docker login
      run: echo ${{ secrets.UPLOAD_TOKEN }} | docker login -u fitbeard --password-stdin docker.pkg.github.com
    - name: Build
      run: bash build_static_only_go.sh

    - name: Release
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: gz
        GHR_PATH: libvirt_exporter
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
